### ISSUE TITLE
BackupStatus and Sequoia

### ISSUE THREAD

**Issue by zormic** [nielsmouthaan/backup-status#11]
Hello,

Just wanted to check if the problem is on my side after installing Sequoia or there is a problem with the app itself. 

When clicking on Backup Disk, Loading is shown briefly and then instead of revealing  the disk menu it just shows a tiny portion of drop menu.

Here are the screenshots of the behaviour under Mac OS 15:

<img width="390" alt="SCR-20240917-mfzg" src="https://github.com/user-attachments/assets/e4644717-ee3a-4800-8cd7-7525c2ff3c02">

![SCR-20240917-mfyg](https://github.com/user-attachments/assets/2735dfce-8e07-41e2-bc9c-d850028714d6)
<img width="180" alt="SCR-20240917-mfvf" src="https://github.com/user-attachments/assets/9f189055-3d19-44b6-ac63-6ad8f0389ecf">

**Comment by dermarkusauslb** [comment]
same here...

**Comment by nielsmouthaan** [comment]
Duplicate of issue #10. See [this comment](https://github.com/nielsmouthaan/backup-status/issues/10#issuecomment-2357685299) for a potential solution.
