### ISSUE TITLE
Backup Status does not work with Mac OS Sequoia ?

### ISSUE THREAD

**Issue by Markus-OSX** [nielsmouthaan/backup-status#13]
Hi, Backup Status will run under Mac OS Sequoia but will not find my TimeMachine Volume (Network). There is no volume listed (yes my TimeMachine works).

<img width="438" alt="Bildschirmfoto 2024-09-21 um 07 31 03" src="https://github.com/user-attachments/assets/e5402e1d-fa8b-4d3b-a565-b6d8baae3402">

Will there be an Update for Mac OS Sequoia ?

Graetz

Markus

**Comment by nielsmouthaan** [comment]
Backup Status only works with locally mounted volumes, hence not with backup disks connected via the network.

**Comment by Markus-OSX** [comment]
Dear Niels,

Backup Status worked well under Mac OS Sonoma with our network attached TimeMachine (still works for my wife’s mac with Sonoma).

Since the Update it does not work anymore, because there is no disk listet.

Is there a way to „re-grant permission“ to the com.apple.TimeMachine.plist file ?

Graetz

Markus


￼￼

**Comment by nielsmouthaan** [comment]
If you're sure the issue is related to Seqoiua, please refer to [this issue](https://github.com/nielsmouthaan/backup-status/issues/10).

**Comment by Markus-OSX** [comment]
Dear Niels, 

thx for the link to the issue.

The tip from EnumC:

"Quick temporary workaround without having to rebuild the project: System Preferences -> Privacy & Security -> Full Disk Access -> Click the plus button and add the app.“

works fine. Now the widget shows the network timemachine volume.

Graetz

Markus
