### ISSUE TITLE
Backup Status not running on OSX 15 Sequoia 

### ISSUE THREAD

**Issue by Hart4IT** [nielsmouthaan/backup-status#15]
Hi Niels,

I use your app Backupstatus 1.0.1, ( and ejectify by the way) but now I have upgraded to MacOS 15 it doesn't work any more?

Can u please help me or update or something? 

The issue is that the widget tells me that the app isn't running but it is. I think they changed the naming of the plist or something.

Please respond, please!

mvg,
Gijs Spruyt
Hart4IT

**Comment by nielsmouthaan** [comment]
Please check [this issue](https://github.com/nielsmouthaan/backup-status/issues/10). Currently, the workaround is to allow full disk access.
