### ISSUE TITLE
Back Up Status doesn't work with MacOS Sequoia 15.01

### ISSUE THREAD

**Issue by maxkot75** [nielsmouthaan/backup-status#17]
Hello together,

pitifully rhe tool doese not work any more with the actuall version of MacOS Sequoia 15.01.

Have you any ideas or solutions to become it work again?

BR
Max

**Comment by nielsmouthaan** [comment]
Please refer to [this issue](https://github.com/nielsmouthaan/backup-status/issues/10). The current workaround is to grant full disk access to Backup Status in System Settings. This issue will hopefully be fixed in Sequioa 15.1.
