### ISSUE TITLE
How to get Backup Status

### ISSUE THREAD

**Issue by PatapoufAdella** [nielsmouthaan/backup-status#7]
I paid the $3 fee to get this package but I never got a link to download it.  Always the same page asking to pay again! 
It is a very bad service.

Send me a link to download the app !

claude.nordmann@bluewin.ch

**Comment by nielsmouthaan** [comment]
That's odd; Gumroad should send you download instructions after payment. Please head to [this article](https://customers.gumroad.com/article/199-how-do-i-access-my-purchase) to find instructions on how to access your purchase. Happy holidays!

**Comment by PatapoufAdella** [comment]
Hello I never got the mail with the link. Please send it again as I want to access to my purchase as quickly as possible. Your system doesn’t work properly!NorBest regards Claude NordmannBouleyres d'amont 78CH 1696 ***@***.*** 26.12.2023 à 14:50, Niels Mouthaan ***@***.***> a écrit :﻿
That's odd; Gumroad should send you download instructions after payment. Please head to this article to find instructions on how to access your purchase. Happy holidays!

**Comment by nielsmouthaan** [comment]
It's not my system, unfortunately. Gumroad handles distribution. But I'll send you a copy manually to your email address.
