### ISSUE TITLE
Grant Permission & Start at Launch options greyed out after re-install

### ISSUE THREAD

**Issue by iandustries** [nielsmouthaan/backup-status#9]
Grant Permission & Start at Launch options greyed out after re-install

![Screenshot 2024-02-15 at 4 00 32 PM](https://github.com/nielsmouthaan/backup-status/assets/18093378/4aa239f7-7a28-4a70-8a2e-7c30e6059cfa)

**Comment by nielsmouthaan** [comment]
This indicates that it's already got the permissions it needs and that it starts at launch. Hence, you should be good.
